### PR TITLE
Small edits and speedups in taxonomy estimation script

### PR DESCRIPTION
**Pull request by akrinos**

### CODE REVIEW

**Comment by halexand** [comment]
PR Should be re-titled to: "Small edits and *massive* speedups ..."

**Comment by halexand** [comment]
Added `transrate` functionality for metaT + made it so that there is a flag to specify if you want to focus on metaT or metaG. Also added some extension specifications.

**Comment by halexand** [comment]
Probably should have just merged and then made a new PR... but so it goes.

**Comment by halexand** [comment]
Everything seems to be good-- I made a few small changes. The main thing was a missing package in one of the environments. Thumbs up from @akrinos and I will merge!

**Comment by akrinos** [comment]
Log files and what not look good to me! I think it's ready to merge in this round.

**Comment by halexand** [comment]
Merged! Wahoo!

**Pull request merged**
